# version: '3'
# services:
#   node-app:
#     container_name: node-app-container
#     build: .
#     volumes:
#       - ./src:/app/src:ro
#     ports:
#       - "4000:4000"
#     env_file:
#       - ./.env
#     # environment:
#     #   - PORT=4000
#     #   - NODE_ENV=production